const { styleBlock, themeColor } = require('./ch3_common');

function getChapter3Overview() {
  return `${styleBlock}
<div style="padding: 4px 2px;">

  <!-- Hero Header Banner -->
  <div style="background: linear-gradient(135deg, rgba(124, 77, 255, 0.22), rgba(83, 109, 254, 0.28)); border: 1.5px solid #7C4DFF; border-radius: 14px; padding: 20px 16px; margin-bottom: 24px; text-align: center; box-shadow: 0 4px 20px rgba(124, 77, 255, 0.25);">
    <div style="font-size: 22px; font-weight: 800; color: #7C4DFF; letter-spacing: 0.5px;">
      ⚡ CHAPTER 3: TRIGONOMETRIC FUNCTIONS
    </div>
    <div style="font-size: 15px; color: #B388FF; font-weight: 600; margin-top: 4px;">
      त्रिकोणमितीय फलन &bull; Class 11 Mathematics Master Reference Guide
    </div>
    <div style="font-size: 13.5px; color: #CBD5E1; margin-top: 8px; line-height: 1.5;">
      Radian &amp; Degree Measures &bull; Unit Circle Definitions &bull; ASTC Quadrant Rules &bull; Compound &amp; Multiple Angle Identities &bull; Trigonometric Equations
    </div>
  </div>

  <!-- Quick Glossary Card -->
  <div style="background: rgba(15, 23, 42, 0.85); border: 1.5px solid rgba(124, 77, 255, 0.45); border-radius: 12px; padding: 16px; margin-bottom: 24px; box-shadow: 0 4px 15px rgba(0,0,0,0.3);">
    <div style="font-size: 17px; font-weight: 800; color: #7C4DFF; margin-bottom: 12px; display: flex; align-items: center; gap: 8px;">
      📖 Quick Glossary &amp; Core Definitions
    </div>
    <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 10px; font-size: 14px; line-height: 1.6;">
      <div style="background: rgba(0,0,0,0.3); padding: 10px; border-radius: 8px; border-left: 3px solid #7C4DFF;">
        <b style="color: #7C4DFF;">Radian Measure:</b> Angle subtended at center of unit circle by an arc of length 1 unit: &theta; = <i>l</i> / <i>r</i>. &pi; rad = 180&deg;.
      </div>
      <div style="background: rgba(0,0,0,0.3); padding: 10px; border-radius: 8px; border-left: 3px solid #7C4DFF;">
        <b style="color: #7C4DFF;">Unit Circle Definition:</b> On circle <i>x</i><sup>2</sup> + <i>y</i><sup>2</sup> = 1, cos &theta; = <i>x</i> and sin &theta; = <i>y</i> for terminal point P(<i>x</i>, <i>y</i>).
      </div>
      <div style="background: rgba(0,0,0,0.3); padding: 10px; border-radius: 8px; border-left: 3px solid #7C4DFF;">
        <b style="color: #7C4DFF;">ASTC Quadrant Rule:</b> All +ve in Q I; Sin/Cosec +ve in Q II; Tan/Cot +ve in Q III; Cos/Sec +ve in Q IV.
      </div>
      <div style="background: rgba(0,0,0,0.3); padding: 10px; border-radius: 8px; border-left: 3px solid #7C4DFF;">
        <b style="color: #7C4DFF;">Periodicity:</b> sin, cos, sec, cosec have fundamental period 2&pi;; tan and cot have period &pi;.
      </div>
      <div style="background: rgba(0,0,0,0.3); padding: 10px; border-radius: 8px; border-left: 3px solid #7C4DFF;">
        <b style="color: #7C4DFF;">Principal Solutions:</b> Solutions of a trigonometric equation in the interval 0 &le; <i>x</i> &lt; 2&pi;.
      </div>
      <div style="background: rgba(0,0,0,0.3); padding: 10px; border-radius: 8px; border-left: 3px solid #7C4DFF;">
        <b style="color: #7C4DFF;">General Solution:</b> The complete set of all integer-parameterised solutions of a trigonometric equation.
      </div>
    </div>
  </div>

  <!-- Section 3.1: Angles & Measure Systems -->
  <div style="margin-bottom: 26px;">
    <h2 style="color: #7C4DFF; font-size: 19px; font-weight: 800; border-bottom: 2px solid rgba(124, 77, 255, 0.4); padding-bottom: 6px; margin-bottom: 12px;">
      3.1 Angles, Degree &amp; Radian Measures
    </h2>
    <p style="color: #E2E8F0; line-height: 1.85; font-size: 15px; margin-bottom: 12px;">
      An <b style="color: #7C4DFF;">angle</b> is generated by rotating a ray from its initial position to a terminal position around a fixed vertex. If rotation is anti-clockwise, the angle is <b>positive</b>; if clockwise, it is <b>negative</b>. In higher mathematics, the sexagesimal system (degrees) is superseded by the natural <b style="color: #7C4DFF;">circular system (radians)</b>.
    </p>

    <!-- Standalone Unit Circle SVG Diagram Card -->
    <div class="diagram-wrapper">
      <svg viewBox="0 0 380 230" xmlns="http://www.w3.org/2000/svg">
        <rect width="380" height="230" fill="#FFFFFF" rx="8" />
        <text x="190" y="22" font-family="-apple-system, sans-serif" font-size="14" font-weight="bold" fill="#4A148C" text-anchor="middle">The Unit Circle Definition: P(x, y) = (cos θ, sin θ)</text>
        
        <!-- Axes -->
        <line x1="40" y1="125" x2="340" y2="125" stroke="#333333" stroke-width="1.8" />
        <line x1="190" y1="30" x2="190" y2="220" stroke="#333333" stroke-width="1.8" />
        
        <!-- Circle radius 75 -->
        <circle cx="190" cy="125" r="75" fill="none" stroke="#7C4DFF" stroke-width="2.5" />
        
        <!-- Terminal Arm at 45 deg -->
        <line x1="190" y1="125" x2="243" y2="72" stroke="#E91E63" stroke-width="2.5" />
        <circle cx="243" cy="72" r="5" fill="#E91E63" />
        <text x="250" y="65" font-family="-apple-system, sans-serif" font-size="12" font-weight="bold" fill="#C2185B">P(cos θ, sin θ)</text>
        
        <!-- Projection lines -->
        <line x1="243" y1="72" x2="243" y2="125" stroke="#0072FF" stroke-width="1.8" stroke-dasharray="3,3" />
        <line x1="190" y1="125" x2="243" y2="125" stroke="#4CAF50" stroke-width="2.5" />
        
        <!-- Angle Arc -->
        <path d="M 215 125 A 25 25 0 0 0 208 107" fill="none" stroke="#FF5722" stroke-width="2" />
        <text x="216" y="112" font-family="-apple-system, sans-serif" font-size="12" font-weight="bold" fill="#E64A19">θ</text>
        
        <!-- Base and Height labels -->
        <text x="216" y="140" font-family="-apple-system, sans-serif" font-size="11.5" font-weight="bold" fill="#2E7D32">x = cos θ</text>
        <text x="250" y="102" font-family="-apple-system, sans-serif" font-size="11.5" font-weight="bold" fill="#0D47A1">y = sin θ</text>
        
        <!-- Cardinal Points -->
        <text x="272" y="121" font-family="-apple-system, sans-serif" font-size="11" font-weight="600" fill="#333">(1, 0)</text>
        <text x="195" y="44" font-family="-apple-system, sans-serif" font-size="11" font-weight="600" fill="#333">(0, 1)</text>
        <text x="86" y="121" font-family="-apple-system, sans-serif" font-size="11" font-weight="600" fill="#333">(&minus;1, 0)</text>
        <text x="195" y="212" font-family="-apple-system, sans-serif" font-size="11" font-weight="600" fill="#333">(0, &minus;1)</text>
      </svg>
      <div class="diagram-caption">💡 Fundamental Geometric Identity: x² + y² = 1 &rArr; cos² θ + sin² θ = 1</div>
    </div>

    <div style="background: rgba(15, 23, 42, 0.7); border-left: 4px solid #7C4DFF; padding: 12px 14px; border-radius: 6px; line-height: 1.85; font-size: 14.5px;">
      <div>• <b>Fundamental Link:</b> &pi; radians = 180&deg; &nbsp;&rArr;&nbsp; 1 radian = <span class="frac"><span class="num">180&deg;</span><span class="den">&pi;</span></span> &approx; 57&deg; 16&prime; 22&Prime;</div>
      <div>• <b>Degree to Radian:</b> 1&deg; = <span class="frac"><span class="num">&pi;</span><span class="den">180</span></span> radian &approx; 0.01746 radian</div>
      <div>• <b>Arc-Length Relation:</b> In a circle of radius <i>r</i>, an arc of length <i>l</i> subtends angle &theta; (in radians) given by:</div>
      <div style="text-align: center; color: #B388FF; font-weight: 700; font-size: 16px; margin: 4px 0;">&theta; = <span class="frac"><span class="num"><i>l</i></span><span class="den"><i>r</i></span></span> &nbsp;&rArr;&nbsp; <i>l</i> = <i>r</i>&theta;</div>
    </div>
  </div>

  <!-- Section 3.2: ASTC & Signs in Quadrants -->
  <div style="margin-bottom: 26px;">
    <h2 style="color: #7C4DFF; font-size: 19px; font-weight: 800; border-bottom: 2px solid rgba(124, 77, 255, 0.4); padding-bottom: 6px; margin-bottom: 12px;">
      3.2 Domain, Range &amp; Signs Across Quadrants
    </h2>
    <div style="overflow-x: auto; -webkit-overflow-scrolling: touch; margin-bottom: 14px;">
      <table style="width: 100%; border-collapse: collapse; font-size: 13.5px; text-align: center; color: #E2E8F0;">
        <thead>
          <tr style="background: rgba(124, 77, 255, 0.25); color: #B388FF; border-bottom: 2px solid #7C4DFF;">
            <th style="padding: 8px; text-align: left;">Function</th>
            <th style="padding: 8px;">Domain</th>
            <th style="padding: 8px;">Range</th>
            <th style="padding: 8px;">Quadrant I</th>
            <th style="padding: 8px;">Quadrant II</th>
            <th style="padding: 8px;">Quadrant III</th>
            <th style="padding: 8px;">Quadrant IV</th>
          </tr>
        </thead>
        <tbody>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08);">
            <td style="padding: 8px; text-align: left; font-weight: 700; color: #B388FF;">sin <i>x</i></td>
            <td style="padding: 8px;">&reals;</td>
            <td style="padding: 8px;">[&minus;1, 1]</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (0 &rarr; 1)</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (1 &rarr; 0)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (0 &rarr; &minus;1)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (&minus;1 &rarr; 0)</td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08); background: rgba(255,255,255,0.02);">
            <td style="padding: 8px; text-align: left; font-weight: 700; color: #B388FF;">cos <i>x</i></td>
            <td style="padding: 8px;">&reals;</td>
            <td style="padding: 8px;">[&minus;1, 1]</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (1 &rarr; 0)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (0 &rarr; &minus;1)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (&minus;1 &rarr; 0)</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (0 &rarr; 1)</td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08);">
            <td style="padding: 8px; text-align: left; font-weight: 700; color: #B388FF;">tan <i>x</i></td>
            <td style="padding: 8px;">&reals; &minus; {(2<i>n</i>+1)&pi;/2}</td>
            <td style="padding: 8px;">&reals;</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (0 &rarr; &infin;)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (&minus;&infin; &rarr; 0)</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (0 &rarr; &infin;)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (&minus;&infin; &rarr; 0)</td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08); background: rgba(255,255,255,0.02);">
            <td style="padding: 8px; text-align: left; font-weight: 700; color: #B388FF;">cot <i>x</i></td>
            <td style="padding: 8px;">&reals; &minus; {<i>n&pi;</i>}</td>
            <td style="padding: 8px;">&reals;</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (&infin; &rarr; 0)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (0 &rarr; &minus;&infin;)</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (&infin; &rarr; 0)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (0 &rarr; &minus;&infin;)</td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08);">
            <td style="padding: 8px; text-align: left; font-weight: 700; color: #B388FF;">sec <i>x</i></td>
            <td style="padding: 8px;">&reals; &minus; {(2<i>n</i>+1)&pi;/2}</td>
            <td style="padding: 8px;">(&minus;&infin;, &minus;1] &cup; [1, &infin;)</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (1 &rarr; &infin;)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (&minus;&infin; &rarr; &minus;1)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (&minus;1 &rarr; &minus;&infin;)</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (&infin; &rarr; 1)</td>
          </tr>
          <tr>
            <td style="padding: 8px; text-align: left; font-weight: 700; color: #B388FF;">cosec <i>x</i></td>
            <td style="padding: 8px;">&reals; &minus; {<i>n&pi;</i>}</td>
            <td style="padding: 8px;">(&minus;&infin;, &minus;1] &cup; [1, &infin;)</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (&infin; &rarr; 1)</td>
            <td style="padding: 8px; color: #4CAF50;">+ve (1 &rarr; &infin;)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (&minus;&infin; &rarr; &minus;1)</td>
            <td style="padding: 8px; color: #F44336;">&minus;ve (&minus;1 &rarr; &minus;&infin;)</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Master Revision Formula Cheat Sheet -->
  <div style="background: linear-gradient(135deg, rgba(15, 23, 42, 0.95), rgba(40, 10, 80, 0.95)); border: 2px solid #7C4DFF; border-radius: 14px; padding: 18px 16px; margin-top: 26px; box-shadow: 0 4px 25px rgba(124, 77, 255, 0.35);">
    <div style="font-size: 20px; font-weight: 800; color: #B388FF; text-align: center; margin-bottom: 14px; letter-spacing: 0.5px;">
      🏆 MASTER REVISION FORMULA CHEAT SHEET
    </div>
    <div style="overflow-x: auto; -webkit-overflow-scrolling: touch;">
      <table style="width: 100%; border-collapse: collapse; font-size: 14px; text-align: left; color: #E2E8F0;">
        <thead>
          <tr style="background: rgba(124, 77, 255, 0.25); color: #B388FF; border-bottom: 2px solid #7C4DFF;">
            <th style="padding: 10px 12px; font-weight: 700;">Formula Category</th>
            <th style="padding: 10px 12px; font-weight: 700;">Mathematical Identities</th>
          </tr>
        </thead>
        <tbody>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08);">
            <td style="padding: 10px 12px; font-weight: 700; color: #B388FF;">Pythagorean Identities</td>
            <td style="padding: 10px 12px;">
              • sin<sup>2</sup> <i>x</i> + cos<sup>2</sup> <i>x</i> = 1<br/>
              • 1 + tan<sup>2</sup> <i>x</i> = sec<sup>2</sup> <i>x</i><br/>
              • 1 + cot<sup>2</sup> <i>x</i> = cosec<sup>2</sup> <i>x</i>
            </td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08); background: rgba(255,255,255,0.02);">
            <td style="padding: 10px 12px; font-weight: 700; color: #B388FF;">Compound Angles (Sum &amp; Difference)</td>
            <td style="padding: 10px 12px;">
              • sin(A &plusmn; B) = sin A cos B &plusmn; cos A sin B<br/>
              • cos(A &plusmn; B) = cos A cos B &mp; sin A sin B<br/>
              • tan(A &plusmn; B) = <span class="frac"><span class="num">tan A &plusmn; tan B</span><span class="den">1 &mp; tan A tan B</span></span><br/>
              • cot(A &plusmn; B) = <span class="frac"><span class="num">cot A cot B &mp; 1</span><span class="den">cot B &plusmn; cot A</span></span>
            </td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08);">
            <td style="padding: 10px 12px; font-weight: 700; color: #B388FF;">Sum-to-Product (CD Formulas)</td>
            <td style="padding: 10px 12px;">
              • sin C + sin D = 2 sin(<span class="frac"><span class="num">C + D</span><span class="den">2</span></span>) cos(<span class="frac"><span class="num">C &minus; D</span><span class="den">2</span></span>)<br/>
              • sin C &minus; sin D = 2 cos(<span class="frac"><span class="num">C + D</span><span class="den">2</span></span>) sin(<span class="frac"><span class="num">C &minus; D</span><span class="den">2</span></span>)<br/>
              • cos C + cos D = 2 cos(<span class="frac"><span class="num">C + D</span><span class="den">2</span></span>) cos(<span class="frac"><span class="num">C &minus; D</span><span class="den">2</span></span>)<br/>
              • cos C &minus; cos D = &minus;2 sin(<span class="frac"><span class="num">C + D</span><span class="den">2</span></span>) sin(<span class="frac"><span class="num">C &minus; D</span><span class="den">2</span></span>)
            </td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08); background: rgba(255,255,255,0.02);">
            <td style="padding: 10px 12px; font-weight: 700; color: #B388FF;">Double Angle Formulas</td>
            <td style="padding: 10px 12px;">
              • sin 2<i>x</i> = 2 sin <i>x</i> cos <i>x</i> = <span class="frac"><span class="num">2 tan x</span><span class="den">1 + tan<sup>2</sup> x</span></span><br/>
              • cos 2<i>x</i> = cos<sup>2</sup> <i>x</i> &minus; sin<sup>2</sup> <i>x</i> = 2 cos<sup>2</sup> <i>x</i> &minus; 1 = 1 &minus; 2 sin<sup>2</sup> <i>x</i> = <span class="frac"><span class="num">1 &minus; tan<sup>2</sup> x</span><span class="den">1 + tan<sup>2</sup> x</span></span><br/>
              • tan 2<i>x</i> = <span class="frac"><span class="num">2 tan x</span><span class="den">1 &minus; tan<sup>2</sup> x</span></span>
            </td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.08);">
            <td style="padding: 10px 12px; font-weight: 700; color: #B388FF;">Triple Angle Formulas</td>
            <td style="padding: 10px 12px;">
              • sin 3<i>x</i> = 3 sin <i>x</i> &minus; 4 sin<sup>3</sup> <i>x</i><br/>
              • cos 3<i>x</i> = 4 cos<sup>3</sup> <i>x</i> &minus; 3 cos <i>x</i><br/>
              • tan 3<i>x</i> = <span class="frac"><span class="num">3 tan x &minus; tan<sup>3</sup> x</span><span class="den">1 &minus; 3 tan<sup>2</sup> x</span></span>
            </td>
          </tr>
          <tr>
            <td style="padding: 10px 12px; font-weight: 700; color: #B388FF;">General Solutions</td>
            <td style="padding: 10px 12px;">
              • sin &theta; = sin &alpha; &rArr; &theta; = <i>n&pi;</i> + (&minus;1)<sup><i>n</i></sup> &alpha;, &nbsp; <i>n</i> &isin; &integers;<br/>
              • cos &theta; = cos &alpha; &rArr; &theta; = 2<i>n&pi;</i> &plusmn; &alpha;, &nbsp; <i>n</i> &isin; &integers;<br/>
              • tan &theta; = tan &alpha; &rArr; &theta; = <i>n&pi;</i> + &alpha;, &nbsp; <i>n</i> &isin; &integers;
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>
`;
}

const chapter3MCQs = [
  {
    id: "c11-math-ch3-mcq-1",
    question: "The radian measure corresponding to 25° is:",
    options: [
      "A):   π/36 radian",
      "B):   5π/72 radian",
      "C):   5π/36 radian",
      "D):   25π/9 radian"
    ],
    correctAnswer: "C",
    explanation: "Radian measure = Degree × (π/180) = 25 × (π/180) = 5π/36 radian."
  },
  {
    id: "c11-math-ch3-mcq-2",
    question: "The degree measure corresponding to (5π/3) radians is:",
    options: [
      "A):   150°",
      "B):   300°",
      "C):   240°",
      "D):   210°"
    ],
    correctAnswer: "B",
    explanation: "Degree measure = (5π/3) × (180/π) = 5 × 60° = 300°."
  },
  {
    id: "c11-math-ch3-mcq-3",
    question: "A wheel makes 360 revolutions in one minute. Through how many radians does it turn in one second?",
    options: [
      "A):   12π radians",
      "B):   6π radians",
      "C):   24π radians",
      "D):   36π radians"
    ],
    correctAnswer: "A",
    explanation: "Revolutions in 1 second = 360/60 = 6 rev/s. In 6 revolutions, angle = 6 × 2π = 12π radians."
  },
  {
    id: "c11-math-ch3-mcq-4",
    question: "In a circle of radius r, an arc of length l subtends an angle θ at the centre. The correct formula in radians is:",
    options: [
      "A):   θ = r / l",
      "B):   l = θ / r",
      "C):   θ = lr",
      "D):   θ = l / r"
    ],
    correctAnswer: "D",
    explanation: "By definition of radian measure, angle subtended θ = l / r, where l is arc length and r is radius."
  },
  {
    id: "c11-math-ch3-mcq-5",
    question: "In a circle of diameter 40 cm, the chord length is 20 cm. The length of the minor arc of the chord is:",
    options: [
      "A):   10π/3 cm",
      "B):   20π/3 cm",
      "C):   40π/3 cm",
      "D):   20π cm"
    ],
    correctAnswer: "B",
    explanation: "Radius r = 20 cm. Since chord = 20 cm, the triangle with centre is equilateral ⇒ θ = 60° = π/3 rad. Arc length l = rθ = 20 × (π/3) = 20π/3 cm."
  },
  {
    id: "c11-math-ch3-mcq-6",
    question: "If cos x = −1/2 and x lies in the third quadrant, then the value of tan x is:",
    options: [
      "A):   √3",
      "B):   −√3",
      "C):   1/√3",
      "D):   −1/√3"
    ],
    correctAnswer: "A",
    explanation: "In Q III, tan x is positive. sin x = −√(1 − cos² x) = −√3/2. tan x = sin x / cos x = (−√3/2) / (−1/2) = √3."
  },
  {
    id: "c11-math-ch3-mcq-7",
    question: "The value of sin 765° is:",
    options: [
      "A):   1/2",
      "B):   √3/2",
      "C):   1/√2",
      "D):   −1/√2"
    ],
    correctAnswer: "C",
    explanation: "sin 765° = sin(2 × 360° + 45°) = sin 45° = 1/√2."
  },
  {
    id: "c11-math-ch3-mcq-8",
    question: "The value of tan(19π/3) is:",
    options: [
      "A):   1",
      "B):   1/√3",
      "C):   −√3",
      "D):   √3"
    ],
    correctAnswer: "D",
    explanation: "tan(19π/3) = tan(6π + π/3) = tan(π/3) = √3."
  },
  {
    id: "c11-math-ch3-mcq-9",
    question: "The value of cosec(−1410°) is:",
    options: [
      "A):   −2",
      "B):   2",
      "C):   √2",
      "D):   1"
    ],
    correctAnswer: "B",
    explanation: "cosec(−1410°) = cosec(−1410° + 4 × 360°) = cosec(−1410° + 1440°) = cosec 30° = 2."
  },
  {
    id: "c11-math-ch3-mcq-10",
    question: "The fundamental period of the function f(x) = tan x is:",
    options: [
      "A):   π",
      "B):   2π",
      "C):   π/2",
      "D):   4π"
    ],
    correctAnswer: "A",
    explanation: "The tangent and cotangent functions repeat their values every π radians, hence their fundamental period is π."
  },
  {
    id: "c11-math-ch3-mcq-11",
    question: "The exact value of sin 75° is:",
    options: [
      "A):   (√3 − 1) / (2√2)",
      "B):   (√3 + 1) / √2",
      "C):   (√3 + 1) / (2√2)",
      "D):   (√3 − 1) / √2"
    ],
    correctAnswer: "C",
    explanation: "sin 75° = sin(45° + 30°) = sin 45° cos 30° + cos 45° sin 30° = (√3 + 1) / (2√2)."
  },
  {
    id: "c11-math-ch3-mcq-12",
    question: "The value of tan 15° is:",
    options: [
      "A):   2 + √3",
      "B):   2 − √3",
      "C):   √3 − 1",
      "D):   √3 + 1"
    ],
    correctAnswer: "B",
    explanation: "tan 15° = tan(45° − 30°) = (1 − 1/√3) / (1 + 1/√3) = (√3 − 1) / (√3 + 1) = 2 − √3."
  },
  {
    id: "c11-math-ch3-mcq-13",
    question: "The expression sin² 6x − sin² 4x is equal to:",
    options: [
      "A):   cos 2x cos 10x",
      "B):   sin 2x cos 10x",
      "C):   cos 2x sin 10x",
      "D):   sin 2x sin 10x"
    ],
    correctAnswer: "D",
    explanation: "Using identity sin² A − sin² B = sin(A + B) sin(A − B): sin² 6x − sin² 4x = sin 10x sin 2x."
  },
  {
    id: "c11-math-ch3-mcq-14",
    question: "The expression cos 4x can be written in terms of sin x and cos x as:",
    options: [
      "A):   1 − 8 sin² x cos² x",
      "B):   1 − 4 sin² x cos² x",
      "C):   8 cos⁴ x − 1",
      "D):   1 − 2 sin² x"
    ],
    correctAnswer: "A",
    explanation: "cos 4x = 1 − 2 sin² 2x = 1 − 2(2 sin x cos x)² = 1 − 8 sin² x cos² x."
  },
  {
    id: "c11-math-ch3-mcq-15",
    question: "The value of cos(π/4 + x) + cos(π/4 − x) is equal to:",
    options: [
      "A):   2 cos x",
      "B):   √2 sin x",
      "C):   √2 cos x",
      "D):   2 sin x"
    ],
    correctAnswer: "C",
    explanation: "cos(π/4 + x) + cos(π/4 − x) = 2 cos(π/4) cos x = 2(1/√2) cos x = √2 cos x."
  },
  {
    id: "c11-math-ch3-mcq-16",
    question: "The principal solutions of tan x = √3 in the interval [0, 2π) are:",
    options: [
      "A):   π/6 and 7π/6",
      "B):   π/3 and 4π/3",
      "C):   π/3 and 2π/3",
      "D):   π/4 and 5π/4"
    ],
    correctAnswer: "B",
    explanation: "tan x = √3 > 0 in Q I and Q III. x = π/3 and x = π + π/3 = 4π/3."
  },
  {
    id: "c11-math-ch3-mcq-17",
    question: "The general solution of the equation sin x = 0 is:",
    options: [
      "A):   x = nπ, n ∈ ℤ",
      "B):   x = (2n + 1)π/2, n ∈ ℤ",
      "C):   x = 2nπ, n ∈ ℤ",
      "D):   x = nπ/2, n ∈ ℤ"
    ],
    correctAnswer: "A",
    explanation: "sin x = 0 whenever x is an integral multiple of π: x = nπ for n ∈ ℤ."
  },
  {
    id: "c11-math-ch3-mcq-18",
    question: "The general solution of the equation cos x = 1/2 is:",
    options: [
      "A):   x = nπ ± π/6, n ∈ ℤ",
      "B):   x = 2nπ ± π/6, n ∈ ℤ",
      "C):   x = nπ ± π/3, n ∈ ℤ",
      "D):   x = 2nπ ± π/3, n ∈ ℤ"
    ],
    correctAnswer: "D",
    explanation: "cos x = cos(π/3) ⇒ x = 2nπ ± π/3, n ∈ ℤ."
  },
  {
    id: "c11-math-ch3-mcq-19",
    question: "If tan x = −4/3 and x lies in Quadrant II, then the value of tan(x/2) is:",
    options: [
      "A):   −2",
      "B):   1/2",
      "C):   2",
      "D):   −1/2"
    ],
    correctAnswer: "C",
    explanation: "In Q II, π/2 < x < π ⇒ π/4 < x/2 < π/2 (Q I). cos x = −3/5. tan(x/2) = √((1 − cos x)/(1 + cos x)) = √((1 + 3/5)/(1 − 3/5)) = √(8/2) = 2."
  },
  {
    id: "c11-math-ch3-mcq-20",
    question: "If cos x = −1/3 and x lies in Quadrant III, then the value of cos(x/2) is:",
    options: [
      "A):   √3/3",
      "B):   −√3/3",
      "C):   −√6/3",
      "D):   √6/3"
    ],
    correctAnswer: "B",
    explanation: "In Q III, π < x < 3π/2 ⇒ π/2 < x/2 < 3π/4 (Q II, where cos is negative). cos(x/2) = −√((1 + cos x)/2) = −√((1 − 1/3)/2) = −1/√3 = −√3/3."
  },
  {
    id: "c11-math-ch3-mcq-21",
    question: "The maximum value of the expression 3 sin x + 4 cos x is:",
    options: [
      "A):   5",
      "B):   7",
      "C):   1",
      "D):   25"
    ],
    correctAnswer: "A",
    explanation: "The maximum of a sin x + b cos x is √(a² + b²) = √(3² + 4²) = √25 = 5."
  },
  {
    id: "c11-math-ch3-mcq-22",
    question: "The simplified value of (sin 3x + sin x) / (cos 3x + cos x) is:",
    options: [
      "A):   cot 2x",
      "B):   tan x",
      "C):   cot x",
      "D):   tan 2x"
    ],
    correctAnswer: "D",
    explanation: "(2 sin 2x cos x) / (2 cos 2x cos x) = sin 2x / cos 2x = tan 2x."
  },
  {
    id: "c11-math-ch3-mcq-23",
    question: "In two circles, arcs of same length subtend angles 60° and 75° at the centre. The ratio of their radii r₁ : r₂ is:",
    options: [
      "A):   4 : 5",
      "B):   1 : 1",
      "C):   5 : 4",
      "D):   2 : 3"
    ],
    correctAnswer: "C",
    explanation: "l = r₁θ₁ = r₂θ₂ ⇒ r₁/r₂ = θ₂/θ₁ = 75°/60° = 5/4."
  },
  {
    id: "c11-math-ch3-mcq-24",
    question: "The value of cos 6x in terms of powers of cos x is:",
    options: [
      "A):   32 cos⁶ x − 18 cos² x + 1",
      "B):   32 cos⁶ x − 48 cos⁴ x + 18 cos² x − 1",
      "C):   16 cos⁶ x − 24 cos⁴ x + 9 cos² x − 1",
      "D):   64 cos⁶ x − 48 cos⁴ x + 18 cos² x − 1"
    ],
    correctAnswer: "B",
    explanation: "cos 6x = 4 cos³ 2x − 3 cos 2x = 4(2 cos² x − 1)³ − 3(2 cos² x − 1) = 32 cos⁶ x − 48 cos⁴ x + 18 cos² x − 1."
  },
  {
    id: "c11-math-ch3-mcq-25",
    question: "The general solution of the equation sec² 2x = 1 − tan 2x is:",
    options: [
      "A):   x = nπ/4 only",
      "B):   x = nπ + π/4 only",
      "C):   x = nπ ± π/3",
      "D):   x = nπ/2 or x = nπ/2 + 3π/8, n ∈ ℤ"
    ],
    correctAnswer: "D",
    explanation: "1 + tan² 2x = 1 − tan 2x ⇒ tan 2x(tan 2x + 1) = 0 ⇒ tan 2x = 0 (2x = nπ ⇒ x = nπ/2) or tan 2x = −1 (2x = nπ + 3π/4 ⇒ x = nπ/2 + 3π/8)."
  }
];

module.exports = {
  getChapter3Overview,
  chapter3MCQs
};
